### ISSUE TITLE
free-swagger-extends对swagger不生效 没有捕捉到API

### ISSUE THREAD

**Issue by xcbt9527** [yeyan1996/free-swagger#12]
![image](https://user-images.githubusercontent.com/20396146/101301871-0ddf5000-3875-11eb-95bc-8869c87aa070.png)

**Comment by xcbt9527** [comment]
补充一下：我们是v3的文档，可能是版本问题

**Comment by yeyan1996** [comment]
暂时不支持 v3 版本，不过实现起来比较简单，有时间我写个转换

**Comment by yeyan1996** [comment]
研究了下v3转v2貌似没有解决方案，只有v3转v2的

**Comment by yeyan1996** [comment]
你好，现在已经支持v3版本了
