### ISSUE TITLE
一直提示加载失败

### ISSUE THREAD

**Issue by sinbadmaster** [yeyan1996/free-swagger#133]
<img width="729" alt="image" src="https://user-images.githubusercontent.com/40019023/182121665-a89b59d0-daac-429d-94f0-dfdf2d9f9ad2.png">

**Comment by sinbadmaster** [comment]
`
// hooks.js
export const assignSwagger = async (swagger, url) => {
  const { state } = await import("@/state");
  try {
// 这里目前只判断的swagger V2的Metadata情况
// 未对swagger V3的Metadata  openapi兼容，导致swagger文档解析初始化一直无法成功
    if (!swagger?.swagger) return;
    ok = true;
    state.swagger = swagger;
    state.url = url;
    state.parsedSwagger = await SwaggerParser.dereference(
      cloneDeep(state.swagger)
    );
  } catch (e) {
    console.error(e);
    Message.error("swagger 文档解析失败");
  }
};`

**Comment by yeyan1996** [comment]
按理来说插件是做了 V3 -> V2 的转换的，方便的话可以提供错误案例吗，我修复下
https://github.com/yeyan1996/free-swagger/blob/master/packages/core/src/default/index.ts#L42

**Comment by VENI-VIDIVICI** [comment]
> 按理来说插件是做了 V3 -> V2 的转换的，方便的话可以提供错误案例吗，我修复下 https://github.com/yeyan1996/free-swagger/blob/master/packages/core/src/default/index.ts#L42

https://petstore3.swagger.io/ 我打开这个，谷歌插件报相同提示，无法正常使用

**Comment by yeyan1996** [comment]
已修复
