### ISSUE TITLE
新版本自定义模板那会很难点吗

### ISSUE THREAD

**Issue by LDXu** [yeyan1996/free-swagger#154]
5.3.4新版本自定义模板那会很难点吗。
好像没法覆盖

**Comment by LDXu** [comment]
chrome 浏览器插件

**Comment by LDXu** [comment]
mac 108.0.5359.124（正式版本） (x86_64)

**Comment by yeyan1996** [comment]
我试了一下没有问题，看下是不是改错模板了，模板有 js 和 ts 两种
如果改的是 js 模板，复制的是 ts 的代码块，可能会出现你这种情况

**Comment by LDXu** [comment]
不好意思，可以了，可能和我的某个插件冲突了。我禁用其他的就可以了。
