### ISSUE TITLE
支持每个项目的配置

### ISSUE THREAD

**Issue by songlairui** [yeyan1996/free-swagger#3]
- [x] 项目下 .freeswaggerrc 支持
- [x] 配置记住上次选中的分类

**Comment by yeyan1996** [comment]
1. 推荐直接用 api 的方式使用 free-swagger，然后绑定为 node script 即可 
https://github.com/yeyan1996/free-swagger/blob/master/packages/server/README.md#%E7%94%9F%E6%88%90-api-%E6%96%87%E4%BB%B6
2. free-swagger-cli 已支持配置项记忆功能
