### ISSUE TITLE
有Tags但是无法识别

### ISSUE THREAD

**Issue by sudongyuer** [yeyan1996/free-swagger#84]

**Comment by yeyan1996** [comment]
方便提供下 swagger json 文件或者地址么

**Comment by sudongyuer** [comment]
https://petstore3.swagger.io/api/v3/openapi.json

**Comment by yeyan1996** [comment]
这个 url 在我电脑上是可以运行的，方便提供下错误信息和使用方式么

**Comment by yeyan1996** [comment]
已修复，更新谷歌插件/ tampermonkey 版本
