### ISSUE TITLE
Parameters下的header没有识别

### ISSUE THREAD

**Issue by LDXu** [yeyan1996/free-swagger#90]
![image](https://user-images.githubusercontent.com/16568644/143385062-10be96a0-ef23-4992-9277-d20161847617.png)

/** 
 * @description 获取所有账户名下所有设备最新位置信息-移动端 
 * @param {Object} params 
 * @param {string} params.cityCode - 市码
 * @param {string} params.districtCode - 区码
 * @param {string} params.provinceCode - 省码   
**/
export const getAppAllMonitorTrackUsingGET = (params) =>
  axios.request({
    url: `//manage/delivery-car/app/monitor-track/all`,
    method: "get",
    params: params,
    data: {}
  });

后端服务导出json失败。不好意思，没办法提供json
url那多了个/

**Comment by yeyan1996** [comment]
自定义header没有实现，目前提供的是 query/body/path 这三个参数，之后会考虑补上

**Comment by LDXu** [comment]
好的。这个header其实感觉是不规范是，应该全局是一个就够了。然后接口里面也应该少用header这种。
不过生成注释，生成着也没事，直接拷贝以后，能不看网页了最好了😄
