### ISSUE TITLE
游览器插件是否也能支持一下 knife4j生成的文档？

### ISSUE THREAD

**Issue by LDXu** [yeyan1996/free-swagger#91]
很多公司也会使用 knife4j 的文档，所以一般存在两种文档
https://github.com/CodingDocs/springboot-guide/blob/master/docs/basis/swagger.md
一般开发人员的使用场景，大多数情况都是在网页上单个生成。
看看支持方便吗？

**Comment by yeyan1996** [comment]
这个其实比较麻烦，因为得Case by case去写代码，之前在字节的时候用的又是另一套 ui，支持多套 ui 会线性提高维护成本

对于这种情况我个人推荐还是获取 json 后，直接用 free-swagger-cli 生成
https://github.com/yeyan1996/free-swagger/blob/master/packages/cli/README.md

**Comment by LDXu** [comment]
好的，了解，多谢

**Comment by LDXu** [comment]
@yeyan1996   我看userscript里面有window.SwaggerBootstrapUi这个判断，可能就是knife4j 的老版本。但调试本地的8888服务，有时候knife4j 的也支持，有时候又不行了。哈哈，确实兼容的话，好多逻辑。还是使用free-swagger-cli 生成的好
